### ISSUE TITLE
Installed package doesn't contain static/config.yaml

### ISSUE THREAD

**Issue by jdobes** [tomaskrizek/webshare-downloader#2]
On CentOS 8:
```
pip3 install websharecli
webshare sample-config
Traceback (most recent call last):
  File "/usr/local/bin/webshare", line 11, in <module>
    load_entry_point('websharecli==2.0.0', 'console_scripts', 'webshare')()
  File "/usr/local/lib/python3.6/site-packages/websharecli/cli.py", line 83, in main
    functions[args.subparser](args)
  File "/usr/local/lib/python3.6/site-packages/websharecli/cli.py", line 38, in sample_config
    config.CONFIG_FILE
  File "/usr/lib64/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/websharecli/static/config.yaml'
```

**Comment by nicki-krizek** [comment]
Thanks for reporting! There was a typo which didn't affect previous versions for some reason.

Fixed in 2.0.1.
